apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openwebui-data-pvc
  labels:
    app: openwebui
    app.kubernetes.io/name: openwebui
    app.kubernetes.io/component: frontend
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  # storageClassName will be set by overlays (standard for Kind, gp3 for prod)
