apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openwebui-data-pvc
spec:
  storageClassName: standard  # Kind default storage class
  resources:
    requests:
      storage: 500Mi  # Reduced for Kind/e2e testing
