apiVersion: v1
kind: Secret
metadata:
  name: litellm-secrets
  namespace: openwebui
  labels:
    app: litellm
type: Opaque
stringData:
  ANTHROPIC_API_KEY: "sk-ant-YOUR-KEY-HERE"  # Replace with actual key
  LITELLM_MASTER_KEY: "sk-litellm-dev-master-key"  # Simple dev key
---
apiVersion: v1
kind: Secret
metadata:
  name: openwebui-secrets
  namespace: openwebui
  labels:
    app: openwebui
type: Opaque
stringData:
  OPENAI_API_KEY: "sk-litellm-dev-master-key"  # Same as LiteLLM master key
