# golangci-lint configuration for vTeam backend
# Compatible with golangci-lint v2.x
#
# This configuration is pragmatic for a Kubernetes-native application.
# We focus on catching real bugs rather than style issues.

version: "2"

run:
  timeout: 5m

linters:
  enable:
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
  disable:
    - errcheck
