apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: agenticsessions.vteam.ambient-code
spec:
  group: vteam.ambient-code
  versions:
  - name: v1alpha1
    served: true
    storage: true
    subresources:
      status: {}
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            required:
            - prompt
            properties:
              # Multiple-repo configuration (new unified mapping)
              repos:
                type: array
                description: "List of repositories. Each has an input (required) and an optional output mapping."
                items:
                  type: object
                  required:
                  - input
                  properties:
                    input:
                      type: object
                      required:
                      - url
                      properties:
                        url:
                          type: string
                          description: "Input (upstream) Git repository URL"
                        branch:
                          type: string
                          description: "Input branch to checkout"
                          default: "main"
                    output:
                      type: object
                      description: "Optional output (fork/target) repository"
                      properties:
                        url:
                          type: string
                          description: "Output Git repository URL (fork or same as input)"
                        branch:
                          type: string
                          description: "Output branch to push to"
                          default: "main"
                    status:
                      type: string
                      description: "Per-repo state: pushed, abandoned"
                      enum:
                      - "pushed"
                      - "abandoned"
              mainRepoIndex:
                type: integer
                description: "Index of the repo in repos array treated as the main repo (Claude working dir). Defaults to 0 (first repo)."
                default: 0
              interactive:
                type: boolean
                description: "When true, run session in interactive chat mode using inbox/outbox files"
              prompt:
                type: string
                description: "The initial prompt for the agentic session"
              displayName:
                type: string
                description: "A descriptive display name for the agentic session generated from prompt and website"
              userContext:
                type: object
                description: "Authenticated caller identity captured at creation time"
                properties:
                  userId:
                    type: string
                    description: "Stable user identifier (from SSO)"
                  displayName:
                    type: string
                    description: "Human-readable display name"
                  groups:
                    type: array
                    items:
                      type: string
                    description: "Group memberships of the user"
              llmSettings:
                type: object
                properties:
                  model:
                    type: string
                    default: "claude-3-7-sonnet-latest"
                  temperature:
                    type: number
                    default: 0.7
                  maxTokens:
                    type: integer
                    default: 4000
                description: "LLM configuration settings"
              timeout:
                type: integer
                default: 300
                description: "Timeout in seconds for the agentic session"
              autoPushOnComplete:
                type: boolean
                default: false
                description: "When true, the runner will commit and push changes automatically after it finishes"
          status:
            type: object
            properties:
              phase:
                type: string
                enum:
                - "Pending"
                - "Creating"
                - "Running"
                - "Completed"
                - "Failed"
                - "Stopped"
                - "Error"
                default: "Pending"
              message:
                type: string
                description: "Status message or error details"
              startTime:
                type: string
                format: date-time
              completionTime:
                type: string
                format: date-time
              jobName:
                type: string
                description: "Name of the Kubernetes job created for this session"
              stateDir:
                type: string
                description: "Directory path where session state files are stored"
              # Result summary fields from the runner's ResultMessage
              subtype:
                type: string
                description: "Result subtype (e.g., success, error, interrupted)"
              is_error:
                type: boolean
                description: "Whether the run ended with an error"
              num_turns:
                type: integer
                description: "Number of conversation turns in the run"
              session_id:
                type: string
                description: "Runner session identifier"
              total_cost_usd:
                type: number
                description: "Total cost of the run in USD as reported by the runner"
              usage:
                type: object
                description: "Token and request usage breakdown"
                x-kubernetes-preserve-unknown-fields: true
              result:
                type: string
                description: "Final result text as reported by the runner"
    additionalPrinterColumns:
    - name: Phase
      type: string
      description: Current phase of the agentic session
      jsonPath: .status.phase
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp
  scope: Namespaced
  names:
    plural: agenticsessions
    singular: agenticsession
    kind: AgenticSession
    shortNames:
    - as
