apiVersion: v1
kind: Secret
metadata:
  name: langfuse-keys
  namespace: ambient-code
type: Opaque
stringData:
  LANGFUSE_PUBLIC_KEY: "${LANGFUSE_PUBLIC_KEY}"
  LANGFUSE_SECRET_KEY: "${LANGFUSE_SECRET_KEY}"
