-- pgvector Schema for RAG Database
-- This schema supports document storage and vector similarity search
-- PostgreSQL 16+ with pgvector extension required

-- Enable required extensions
CREATE EXTENSION IF NOT EXISTS pgvector;
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- Documents table: Stores metadata about uploaded documents
CREATE TABLE IF NOT EXISTS documents (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    rag_database_name VARCHAR(253) NOT NULL,  -- RAGDatabase CRD name
    document_cr_name VARCHAR(253) NOT NULL,   -- RAGDocument CRD name
    file_path TEXT NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    file_format VARCHAR(10) NOT NULL CHECK (file_format IN ('pdf', 'docx', 'pptx', 'xlsx', 'md', 'csv', 'txt', 'html')),
    uploaded_by VARCHAR(255) NOT NULL,
    upload_timestamp TIMESTAMPTZ NOT NULL,
    chunk_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(rag_database_name, document_cr_name)
);

-- Chunks table: Stores document chunks with vector embeddings
CREATE TABLE IF NOT EXISTS chunks (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    document_id UUID NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
    chunk_index INTEGER NOT NULL,  -- Sequential index within document (0-based)
    text TEXT NOT NULL CHECK (length(text) >= 10 AND length(text) <= 1000),
    embedding VECTOR(384) NOT NULL,  -- Granite 30M English embedding (384 dimensions)
    page_number INTEGER CHECK (page_number >= 1),  -- Optional, for PDFs
    section_reference TEXT,  -- Optional, for structured documents
    metadata JSONB,  -- Additional metadata (headings, tables, etc.)
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(document_id, chunk_index)
);

-- Indexes for performance

-- HNSW index for fast vector similarity search
-- m = 16: Number of connections per layer (default: 16, range: 2-100)
-- ef_construction = 64: Size of dynamic candidate list for construction (default: 64)
-- vector_cosine_ops: Cosine similarity operator for normalized vectors
CREATE INDEX IF NOT EXISTS chunks_embedding_idx
    ON chunks
    USING hnsw (embedding vector_cosine_ops)
    WITH (m = 16, ef_construction = 64);

-- Full-text search index for hybrid search (keyword + vector)
CREATE INDEX IF NOT EXISTS chunks_text_idx
    ON chunks
    USING GIN (to_tsvector('english', text));

-- Index for document lookups
CREATE INDEX IF NOT EXISTS chunks_document_id_idx
    ON chunks(document_id);

-- Index for RAG database queries
CREATE INDEX IF NOT EXISTS documents_rag_database_idx
    ON documents(rag_database_name);

-- Comments for documentation
COMMENT ON TABLE documents IS 'Stores metadata about uploaded documents in RAG databases';
COMMENT ON TABLE chunks IS 'Stores document chunks with vector embeddings for semantic search';
COMMENT ON COLUMN chunks.embedding IS 'Vector embedding (384 dimensions) generated by Granite 30M English model';
COMMENT ON INDEX chunks_embedding_idx IS 'HNSW index for fast approximate nearest neighbor search';
COMMENT ON INDEX chunks_text_idx IS 'GIN index for full-text search (hybrid search support)';
