# golangci-lint configuration for vTeam operator
# Compatible with golangci-lint v2.x
#
# Pragmatic configuration for Kubernetes operator development.

version: "2"

run:
  timeout: 5m

linters:
  enable:
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
  disable:
    - errcheck
